<?php

namespace app\modules\studentid\models;

class StudentIdRequest extends \app\models\SmStudentIdRequest
{

    public static function tableName(): string
    {
        return parent::tableName();
    }

    public function attributeLabels(): array
    {
        $labels = parent::attributeLabels();

        $labels['request_type_id'] = 'Request type';
        $labels['request_date'] = 'Request date';
        $labels['status_id'] = 'Request status';
        $labels['source'] = 'Request reason';

        return $labels;
    }

    public function attributeHints(): array
    {
        $hints = parent::attributeHints(); // TODO: Change the autogenerated stub

        $hints['source'] = 'ID request reason';
        return $hints;
    }
}