<?php

use yii\db\Migration;

/**
 * Class m221205_124245_create_sm_student_id_request_sequence
 */
class m221205_124245_create_sm_student_id_request_sequence extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $sql = <<<SQL
ALTER TABLE "smis"."sm_student_id_request" 
  ALTER COLUMN "request_id" ADD GENERATED BY DEFAULT AS IDENTITY;
SQL;


        $this->execute($sql);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m221205_124245_create_sm_student_id_request_sequence cannot be reverted.\n";

        return false;
    }
}
